site_name: ExpressLRS
site_url: https://expresslrs.github.io/Website/
#site_url: https://www.expresslrs.org/
site_author: ExpressLRS
site_description: >-
  ExpressLRS aims to provide the best completely open, high refresh radio
  control link while maintaining a maximum achievable range at that rate with
  low latency. Vast support of hardware in both 900 Mhz and 2.4 GHz frequencies.

# Repository
repo_name: ExpressLRS/ExpressLRS
repo_url: https://github.com/ExpressLRS/ExpressLRS
edit_uri: "https://github.com/ExpressLRS/Website/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2021 Team ExpressLRS

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: expresslrs
      accent: expresslrs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/images/logotype.svg
  icon:
    logo: logo

plugins:
  - search
  #  - redirects:
  - minify:
      minify_html: true
      

extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/colors.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ExpressLRS/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dS6ReFY
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/636441730280366
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/expresslrs
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/expresslrs

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ExpressLRS
      repo: ExpressLRS
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quick Start:
      - Getting Started: quick-start/getting-started.md
      - Installing Configurator: quick-start/installing-configurator.md
      - Selecting Your Target: quick-start/your-target.md
      - Flashing Bootloader: quick-start/flashing-bootloader.md
      - Setting User Defines: quick-start/user-defines.md
      - Setting Firmware Options: quick-start/firmware-options.md
      - Flashing ExpressLRS: quick-start/flashing-elrs.md
      - Configuring OpenTX: quick-start/otx-cfg.md
      - Configuring Betaflight: quick-start/bf-cfg.md
      - Binding ExpressLRS: quick-start/binding.md
  - Software:
      - Switch Configs: software/switch-config.md
  - Info:
      - Signal Health: info/signal-health.md
      - Telemetry Bandwith: info/telem-bandwidth.md
  - FAQ: faq.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv [ "GOOGLE_ANALYTICS_KEY" ]
  - auto
